--- 
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
---

# About us {-}

<hr style="border:2px solid gray"> </hr>

<div class="page-body">
  <h1 id="678b2ea1-d651-499f-9021-cd087067215b" class="">
    연구분야 및 구성원 소개
  </h1>
  <hr id="9585eb11-0382-4474-853e-be81f2e01658" />
  <h2 id="521d286a-db79-4f91-82a4-0e3182280b64" class="">연구분야</h2>
  <ul id="cc74cfe7-2885-4518-b8a0-62fc17668238" class="bulleted-list">
    <li style="list-style-type: disc">Bayesian Computation</li>
  </ul>
  <ul id="9a3a6c73-a849-4531-bd5d-d733f7598504" class="bulleted-list">
    <li style="list-style-type: disc">Network Analysis</li>
  </ul>
  <ul id="0581e13b-36b2-4dd0-bdea-8e33fefb1953" class="bulleted-list">
    <li style="list-style-type: disc">Spatial Data Analysis</li>
  </ul>
  <ul id="3c76ce6f-0134-4384-80e6-c5b90312d416" class="bulleted-list">
    <li style="list-style-type: disc">Latent Variable Model</li>
  </ul>
  <ul id="d0ef571b-cb2d-4017-90a3-ffd4d3faf7c4" class="bulleted-list">
    <li style="list-style-type: disc">
      Bayesian Adaptive Clinical Trial
    </li>
  </ul>
  <h2 id="e8272e1f-0233-4ec0-9ecc-f3b0ce301995" class="">구성원</h2>
  <ul id="298ecea7-32c4-4ff4-9a46-d2a68cc1300c" class="bulleted-list">
    <li style="list-style-type: disc">박사과정: 4명</li>
  </ul>
  <ul id="2286ee5f-9b0a-497b-92b5-50c0601c9941" class="bulleted-list">
    <li style="list-style-type: disc">
      석사과정: 9명 (석박통합과정 2명 포함)
    </li>
  </ul>
  <ul id="2286ee5f-9b0a-497b-92b5-50c0601c9941" class="bulleted-list">
    <li style="list-style-type: disc">
      학부연구생: 2명
    </li>
  </ul>
  <ul id="a453a88e-35c7-4214-bc56-3a75f0f25203" class="bulleted-list">
    <li style="list-style-type: disc">
      랩장: 박진아 (pja0707@yonsei.ac.kr)
    </li>
  </ul>
  <ul id="6bdf73f9-39e5-4446-aa78-5ac2c5583a66" class="bulleted-list">
    <li style="list-style-type: disc">
      랩에 관해 문의가 있을 경우 랩장 박진아 박사과정에게 문의하면
      성실하게 대답해줄 것임.
    </li>
  </ul>
  <h1 id="fcb411dd-a227-4753-a984-7a81beda848a" class="">
    연구실 시스템
  </h1>
  <hr id="ed984a62-1abf-4007-9974-7596d620154a" />
  <ul id="bd131629-0768-41e3-9fe3-81361fa641d1" class="bulleted-list">
    <li style="list-style-type: disc">
      석사 1학기의 경우 연구실 소속 신입생들끼리 모여 신입생 스터디를
      진행함.
    </li>
  </ul>
  <ul id="36b92f2d-ad42-4882-b5ad-73be175a4ff1" class="bulleted-list">
    <li style="list-style-type: disc">
      신입생 스터디 내용
      <ul id="07a8edef-7e74-4a67-b1cb-9688065e9822" class="bulleted-list">
        <li style="list-style-type: circle">
          기본적인 네트워크 통계 모형에 대한 학습.
        </li>
      </ul>
      <ul id="0393d4f5-88b5-41d5-a396-eca57d8929f7" class="bulleted-list">
        <li style="list-style-type: circle">
          기본적인 프로그래밍 숙달 (C, C++, RCpp).
        </li>
      </ul>
    </li>
  </ul>
  <ul id="458167ce-1614-4c8c-b6fb-ddc2c033cc56" class="bulleted-list">
    <li style="list-style-type: disc">
      석사 2학기부터 본격적인 연구 시작.
      <ul id="0c72bcac-fff5-4a3e-839d-9347a90cafd1" class="bulleted-list">
        <li style="list-style-type: circle">
          학위 논문 과정의 경우 연구 논문 작성.
        </li>
      </ul>
      <ul id="9644abce-e3c2-404f-9b82-2bff46e3e284" class="bulleted-list">
        <li style="list-style-type: circle">
          비학위 논문 과정의 경우 리뷰 논문 작성.
        </li>
      </ul>
    </li>
  </ul>
  <ul id="67e79692-fffa-4a73-a73e-52461563f178" class="bulleted-list">
    <li style="list-style-type: disc">
      현재 학생 실적
      <ul id="505578b2-d085-4a40-afae-cc5396ae6e73" class="bulleted-list">
        <li style="list-style-type: circle">
          박사과정 학생 논문 4편 투고 중 (AOAS, BA, Plos One,
          Psychometrika)
        </li>
      </ul>
      <ul id="0eb8f9bb-e347-4d8b-8808-42c9b2b9c426" class="bulleted-list">
        <li style="list-style-type: circle">
          박사과정 학생 논문 2편 / 석사과정 학생 논문 1편 투고 예정
          (Biometrics, JSS, JASA)
        </li>
      </ul>
    </li>
  </ul>
  <h1 id="788356fa-1b88-4eb0-bcdf-c65969aecf03" class="">
    현재 관심있는 연구 주제
  </h1>
  <hr id="10d95052-9c7e-41fa-9b4c-9b93a405d258" />
  <ul id="80fd22cd-025b-4d76-bd72-a72e2dc1aa0e" class="bulleted-list">
    <li style="list-style-type: disc">
      연결 시간 및 전달 속도를 가진 네트워크 분석.
    </li>
  </ul>
  <ul id="23823cd4-0724-44f4-8ce5-3d6ce941dd2f" class="bulleted-list">
    <li style="list-style-type: disc">
      복수의 네트워크를 가지고 있는 두 집단 간의 차이 검정 및 군집 분석.
    </li>
  </ul>
  <ul id="810f9a0b-92b6-441e-953d-134bf720f7ef" class="bulleted-list">
    <li style="list-style-type: disc">
      네트워크 군집 내에서의 각 구성원들 간의 트리 구조 파악.
    </li>
  </ul>
  <ul id="b8fd0fd0-295b-4b3a-8b88-1e28c1bfe82f" class="bulleted-list">
    <li style="list-style-type: disc">사회적 영향과 선택 분석.</li>
  </ul>
  <ul id="acd34cd4-21db-44c7-ac2e-d8ff677d2f27" class="bulleted-list">
    <li style="list-style-type: disc">네트워크 차원 축소.</li>
  </ul>
  <ul id="c0567a60-8cbd-442a-88ed-d147f2ae2ffe" class="bulleted-list">
    <li style="list-style-type: disc">
      공간이 네트워크 구조에 주는 영향 분석.
    </li>
  </ul>
  <ul id="fff5e261-5a85-4d2b-8585-e88cad0fd177" class="bulleted-list">
    <li style="list-style-type: disc">
      베이지안 적응 할당을 이용한 치료법 추천 알고리즘 개발.
    </li>
  </ul>
  <h1 id="faaca72e-e0e7-4ef2-94ac-44ee3391b004" class="">
    연구원이 얘기하는 연구실의 장단점
  </h1>
  <hr id="cb87e423-a93a-4f1a-8975-0d75daade01d" />
  <ul id="c5491dfc-b6f5-45b5-b483-11978e539a1f" class="bulleted-list">
    <li style="list-style-type: disc">
      장점
      <ul id="f123ebe8-02d1-4081-bff9-91e4de19cf99" class="bulleted-list">
        <li style="list-style-type: circle">
          여러 주제에 대한 연구 기회가 많다.
        </li>
      </ul>
      <ul id="b687fd5c-6f1f-47a6-8547-4a7c92e146e2" class="bulleted-list">
        <li style="list-style-type: circle">
          교수님께서 학생이 따라오는 수준을 고려해서 방향을 잡고
          인도해주신다.
        </li>
      </ul>
      <ul id="1bfcc5e0-4430-43f7-aafd-f679216bb575" class="bulleted-list">
        <li style="list-style-type: circle">
          최신의 연구를 할 수 있도록 교수님께서 방향을 잡아주신다.
        </li>
      </ul>
      <ul id="6e5f0681-a5da-4718-a3a1-cf3600e5d2aa" class="bulleted-list">
        <li style="list-style-type: circle">
          면담을 자주 하면서 다방면으로 관리를 잘 해주신다.
        </li>
      </ul>
      <ul id="4d08a41d-cada-4c9e-9d71-7903bce8b553" class="bulleted-list">
        <li style="list-style-type: circle">
          연구실에 서로 잘 챙겨주는 문화가 있고 서로 많이 도와준다.
        </li>
      </ul>
      <ul id="af1eaa3e-9da2-4cc4-b443-f86d19393a8c" class="bulleted-list">
        <li style="list-style-type: circle">
          연구실 사람들의 관심사가 다양하다.
        </li>
      </ul>
      <ul id="0e3500fe-9139-482b-9230-4a5f65471e75" class="bulleted-list">
        <li style="list-style-type: circle">
          교수님과 연락이 잘된다. (빠르다)
        </li>
      </ul>
      <ul id="25f1b335-4abb-4ee2-bea4-79fd88b493de" class="bulleted-list">
        <li style="list-style-type: circle">
          학생들이 재정적으로 도움을 받을 수 있도록 노력해주신다.
        </li>
      </ul>
      <ul id="80f56935-f5ff-4401-8047-a0be16b058bc" class="bulleted-list">
        <li style="list-style-type: circle">
          교수님의 인적 네트워크가 탄탄하시다.
        </li>
      </ul>
    </li>
  </ul>
  <ul id="52af58cd-cdff-4000-b1a8-5325441a1985" class="bulleted-list">
    <li style="list-style-type: disc">
      단점
      <ul id="9bd2522e-e301-429c-9903-de5a8fdfa7ca" class="bulleted-list">
        <li style="list-style-type: circle">
          지도제자 수가 다른곳에 비해 많은 편이다.
        </li>
      </ul>
      <ul id="ba8cb700-c64a-4c39-81ee-fce421f23d39" class="bulleted-list">
        <li style="list-style-type: circle">
          교수님과 연구스타일이 맞지 않으면 힘들 수도 있다.
        </li>
      </ul>
      <ul id="a7acbcfb-2cb8-43f1-9b82-121891b00c27" class="bulleted-list">
        <li style="list-style-type: circle">
          수업과 병행할때 일이 조금 많아질 수도 있다.
        </li>
      </ul>
      <ul id="be72caee-feae-4fdd-b495-ab403b53f128" class="bulleted-list">
        <li style="list-style-type: circle">
          교수님이랑 미팅할 때 빛 반사로 인해 눈이 너무 부신다.
        </li>
      </ul>
    </li>
  </ul>
  <p id="0d8c4c7c-9349-4de5-8554-65ab714f7f52" class=""></p>
  <p id="c1284f98-f575-4a56-b2ad-d8e53bd23dd5" class=""></p>
</div>

<hr style="border:2px solid gray"> </hr>

<!-- ```{r, eval=FALSE} -->
<!-- bookdown::render_book() -->
<!-- ``` -->


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
